//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_PROJEKT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class artikli
    {
        public artikli()
        {
            this.stavke_izdatnice = new HashSet<stavke_izdatnice>();
            this.stavke_narudzbenice = new HashSet<stavke_narudzbenice>();
            this.stavke_primke = new HashSet<stavke_primke>();
            this.stavke_racuna = new HashSet<stavke_racuna>();
        }
    
        public int id_artikli { get; set; }
        public string naziv { get; set; }
        public int kolicina { get; set; }
        public Nullable<int> id_vrsta_artikla { get; set; }
        public Nullable<decimal> cijena { get; set; }
        public Nullable<int> optimalna { get; set; }
    
        public virtual vrsta_artikla vrsta_artikla { get; set; }
        public virtual ICollection<stavke_izdatnice> stavke_izdatnice { get; set; }
        public virtual ICollection<stavke_narudzbenice> stavke_narudzbenice { get; set; }
        public virtual ICollection<stavke_primke> stavke_primke { get; set; }
        public virtual ICollection<stavke_racuna> stavke_racuna { get; set; }
    }
}
