//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_PROJEKT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class narudzbenica
    {
        public narudzbenica()
        {
            this.stavke_narudzbenice = new HashSet<stavke_narudzbenice>();
        }
    
        public int id_narudzbenica { get; set; }
        public System.DateTime datum { get; set; }
        public Nullable<int> id_korisnik { get; set; }
        public Nullable<int> id_poslovni_partner { get; set; }
        public string izdaje { get; set; }
    
        public virtual korisnici korisnici { get; set; }
        public virtual poslovni_partner poslovni_partner { get; set; }
        public virtual ICollection<stavke_narudzbenice> stavke_narudzbenice { get; set; }
    }
}
