//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_PROJEKT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class primka
    {
        public primka()
        {
            this.stavke_primke = new HashSet<stavke_primke>();
        }
    
        public int id_primka { get; set; }
        public System.DateTime datum { get; set; }
        public Nullable<int> id_korisnik { get; set; }
        public string izdaje { get; set; }
    
        public virtual korisnici korisnici { get; set; }
        public virtual ICollection<stavke_primke> stavke_primke { get; set; }
    }
}
