//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_PROJEKT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class racun
    {
        public racun()
        {
            this.stavke_racuna = new HashSet<stavke_racuna>();
        }
    
        public int id_racun { get; set; }
        public System.DateTime datum { get; set; }
        public Nullable<int> id_korisnik { get; set; }
        public string izdaje { get; set; }
        public string imePrezimeKupca { get; set; }
        public string adresaKupca { get; set; }
        public string oibKupca { get; set; }
        public Nullable<decimal> iznos { get; set; }
    
        public virtual korisnici korisnici { get; set; }
        public virtual ICollection<stavke_racuna> stavke_racuna { get; set; }
    }
}
