//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_PROJEKT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vrsta_artikla
    {
        public vrsta_artikla()
        {
            this.artikli = new HashSet<artikli>();
        }
    
        public int id_vrsta_artikla { get; set; }
        public string naziv { get; set; }
    
        public virtual ICollection<artikli> artikli { get; set; }
    }
}
